name: Test Linux Runner

on:
  workflow_dispatch:
permissions:
  contents: read  

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
    - name: Test Action
      uses: irongut/CodeCoverageSummary@master
      with:
        filename: /src/coverage.*.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
